name: Go Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:26.0-rc-dind-rootless
        ports:
          - 2375:2375

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Run tests
      run: go test -v ./...

